name: "Beszel Agent Branch"
description: "Beszel Agent for HASSIO" 
version: "0.12.0"
slug: "hassio_beszel_agent"
init: false
host_network: true
docker_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  45876/tcp: 45876
image: "ghcr.io/obamium69/hassio_beszel_agent-{arch}"
options:
  key: null
schema:
  key: "password"
