name: "Beszel Agent Dev Branch"
description: "Beszel Agent for HASSIO (Dev Branch)"
version: "0.0.10"
slug: "beszel_agent_dev"
init: false
legacy: true
arch:
  - amd64
  - armhf
  - armv7
options:
  KEY: "default_value"
  NICS: ""
schema:
  KEY:
    description: "Enter the secret key"  # Beschreibung für KEY
    type: password
  NICS:
    description: "Optional: Specify NICs (leave empty if not needed)"  # Beschreibung für NICS
    type: string
ports:
  45876/tcp: 45876
