name: "Beszel Agent Branch"
description: "Beszel Agent for HASSIO" 
version: "0.12.4"
slug: "hassio_beszel_agent"
init: false
host_network: true
docker_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  45876/tcp: 45876
image: "ghcr.io/obamium69/hassio_beszel_agent-{arch}"
options:
  key: ""
  hub_url: ""
  token: ""
  environment_vars:
    - name: EXAMPLE_VAR_NAME
      value: EXAMPLE_VAR_VALUE

schema:
  key: "password"
  hub_url: "str?"
  token: "password?"
  environment_vars:
      - name: "str"
        value: "str"
map:
  - type: data
    read_only: false
    path: /var/lib/beszel-agent