name: "Beszel Agent Main Branch"
description: "Beszel Agent for HASSIO"
version: "0.10.1"
slug: "beszel_agent"
init: false
legacy: true
host_network: true
arch:
  - amd64
  - armhf
  - armv7
options:
  KEY: "default_value"
schema:
  KEY: "password"
ports:
  45876/tcp: 45876
