name: Build and Push Home Assistant Image

on:
  workflow_dispatch:

jobs:
  build-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get latest release version
        id: get_version
        run: |
          VERSION=$(curl -s https://api.github.com/repos/henrygd/beszel/releases/latest | jq -r .tag_name)
          VERSION=$(echo "$VERSION" | sed 's/^v//')
          echo "Latest version: $VERSION"
          echo "::set-output name=VERSION::$VERSION"

      - name: Check if config file version is up-to-date
        id: check_version
        run: |
          CONFIG_VERSION=$(grep '^version:' beszel_agent_dev/config.yaml | sed -E 's/version: "(.*)"/\1/')
          echo "Config version: $CONFIG_VERSION"
          if [ "$CONFIG_VERSION" = "${{ steps.get_version.outputs.VERSION }}" ]; then
            echo "Version is up-to-date. Skipping further steps."
            echo "::set-output name=run_steps::false"
          else
            echo "Version is outdated. Proceeding with updates."
            echo "::set-output name=run_steps::true"
          fi
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}

      - name: Update version in beszel_agent config file
        run: |
          sed -i "s/^version:.*/version: \"${{ steps.get_version.outputs.VERSION }}\"/" beszel_agent_dev/config.yaml
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}

      - name: Login to DockerHub
        #if: ${{ steps.check_version.outputs.run_steps == 'true' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Publish Home Assistant Image
        #if: ${{ steps.check_version.outputs.run_steps == 'true' }}
        uses: home-assistant/builder@2025.02.0
        with:
          args: |
            --all \
            --target beszel_agent_dev \
            --docker-hub ghcr.io/obamium69

      - name: Commit beszel_agent_dev config.yaml version update
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add beszel_agent_dev/config.yaml
          git commit -m "Update beszel_agent_dev config version to ${VERSION}" || echo "No changes to commit"
          git push
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}      
