name: Build and Push Docker Image

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest release version
        id: get_version
        run: |
          VERSION=$(curl -s https://api.github.com/repos/henrygd/beszel/releases/latest | jq -r .tag_name)
          VERSION=$(echo "$VERSION" | sed 's/^v//')
          echo "Latest version: $VERSION"
          echo "::set-output name=VERSION::$VERSION"

      - name: Update version in beszel_agent config file
        run: |
          sed -i "s/^version:.*/version: \"${{ steps.get_version.outputs.VERSION }}\"/" beszel_agent/config.yaml
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}

      - name: Build Docker image for beszel_agent
        run: |
          docker build -t ghcr.io/obamium69/hassio_beszel_agent:${VERSION} ./beszel_agent/
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Push Docker image for beszel_agent
        run: |
          docker push ghcr.io/obamium69/hassio_beszel_agent:${VERSION}
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}

      - name: Commit beszel_agent config.yaml version update
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add beszel_agent/config.yaml
          git commit -m "Update beszel_agent config version to ${VERSION}" || echo "No changes to commit"
          git push
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
